---
tasks:
- name: features admin definitions
  scripts:
    rspec:
      body: DISPLAY=":$XVNC_PORT" bundle exec rspec "spec/features/admin/definitions_spec.rb"
- name: features admin executors
  scripts:
    rspec:
      body: DISPLAY=":$XVNC_PORT" bundle exec rspec "spec/features/admin/executors_spec.rb"
- name: features admin repositories
  scripts:
    rspec:
      body: DISPLAY=":$XVNC_PORT" bundle exec rspec "spec/features/admin/repositories_spec.rb"
- name: features admin timeout_settings
  scripts:
    rspec:
      body: DISPLAY=":$XVNC_PORT" bundle exec rspec "spec/features/admin/timeout_settings_spec.rb"
- name: features admin users
  scripts:
    rspec:
      body: DISPLAY=":$XVNC_PORT" bundle exec rspec "spec/features/admin/users_spec.rb"
- name: features admin view_service_stati
  scripts:
    rspec:
      body: DISPLAY=":$XVNC_PORT" bundle exec rspec "spec/features/admin/view_service_stati_spec.rb"
- name: features admin welcome_page
  scripts:
    rspec:
      body: DISPLAY=":$XVNC_PORT" bundle exec rspec "spec/features/admin/welcome_page_spec.rb"
- name: features public attachments
  scripts:
    rspec:
      body: DISPLAY=":$XVNC_PORT" bundle exec rspec "spec/features/public/attachments_spec.rb"
- name: features public badges_small
  scripts:
    rspec:
      body: DISPLAY=":$XVNC_PORT" bundle exec rspec "spec/features/public/badges_small_spec.rb"
- name: features public badges
  scripts:
    rspec:
      body: DISPLAY=":$XVNC_PORT" bundle exec rspec "spec/features/public/badges_spec.rb"
- name: features public public_page
  scripts:
    rspec:
      body: DISPLAY=":$XVNC_PORT" bundle exec rspec "spec/features/public/public_page_spec.rb"
- name: features public sign_in
  scripts:
    rspec:
      body: DISPLAY=":$XVNC_PORT" bundle exec rspec "spec/features/public/sign_in_spec.rb"
- name: features public sumarry_badges
  scripts:
    rspec:
      body: DISPLAY=":$XVNC_PORT" bundle exec rspec "spec/features/public/sumarry_badges_spec.rb"
- name: features workspace account
  scripts:
    rspec:
      body: DISPLAY=":$XVNC_PORT" bundle exec rspec "spec/features/workspace/account_spec.rb"
- name: features workspace commits
  scripts:
    rspec:
      body: DISPLAY=":$XVNC_PORT" bundle exec rspec "spec/features/workspace/commits_spec.rb"
- name: features workspace execution
  scripts:
    rspec:
      body: DISPLAY=":$XVNC_PORT" bundle exec rspec "spec/features/workspace/execution_spec.rb"
- name: features workspace executions
  scripts:
    rspec:
      body: DISPLAY=":$XVNC_PORT" bundle exec rspec "spec/features/workspace/executions_spec.rb"
- name: features workspace results
  scripts:
    rspec:
      body: DISPLAY=":$XVNC_PORT" bundle exec rspec "spec/features/workspace/results_spec.rb"
- name: features workspace session
  scripts:
    rspec:
      body: DISPLAY=":$XVNC_PORT" bundle exec rspec "spec/features/workspace/session_spec.rb"
- name: features workspace task
  scripts:
    rspec:
      body: DISPLAY=":$XVNC_PORT" bundle exec rspec "spec/features/workspace/task_spec.rb"
- name: features workspace tasks
  scripts:
    rspec:
      body: DISPLAY=":$XVNC_PORT" bundle exec rspec "spec/features/workspace/tasks_spec.rb"
- name: features workspace trial
  scripts:
    rspec:
      body: DISPLAY=":$XVNC_PORT" bundle exec rspec "spec/features/workspace/trial_spec.rb"
