
default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 25
  username: thomas
  password: thomas
 
development:
  <<: *default
  database: cider_ci_development

test: &test
  <<: *default
  database: cider_ci_test

production:
  database: cider_ci_production
  <<: *default

