default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 3
  username: cider-ci
  password: cider-ci
  database: cider-ci_v3_development

development:
  <<: *default

test: &test
  <<: *default
  database: cider-ci_v3_test

production:
  <<: *default
  #database: cider-ci_v3_production


