default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 10
  username: cider-ci
  password: cider-ci
 
development:
  <<: *default
  database: cider-ci_development

test: &test
  <<: *default
  database: cider-ci_test

production:
  database: cider-ci_production
  <<: *default

