default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 3
  username: cider-ci
  password: secret
  database: cider-ci_v3_development
  variables:
    statement_timeout: 3000

development:
  <<: *default

test: &test
  <<: *default
  database: cider-ci_v3_test

production:
  <<: *default
  #database: cider-ci_v3_production


