git:
  repositories_path: "../tmp/repositories"

http_server:
  host: 127.0.0.1
  port: 8888
  ssl: false


messaging: 

  connection: 

    vhost: cider-ci-dev 
    username: user
    password: user
    host: 192.168.0.102

  default_message_expiration: 1

  exchanges:
    - name: branch_event_topic
      type: topic
      durable: true


