release: 
  version_major: 1
  version_minor: 7
  version_patch: x
  version_pre: null
  version_build: null

git:
  repositories_path: <%= Rails.root.join("..","tmp", "repositories").to_s %>

storage_http_prefix: http://127.0.0.1:8883/cider-ci/storage

api_http_prefix: http://127.0.0.1:8885
api_path: '/cider-ci/api/v1'


http_server:
  host: 127.0.0.1
  port: 8888
  ssl: false


messaging: 

  connection: 

    vhost: cider-ci
    username: guest
    password: guest
    host: 127.0.0.1

  exchanges:
    - name: branch_event_topic
      type: topic
      durable: true


