release: 
  version_major: 2
  version_minor: 3
  version_patch: 0
  version_pre: development
  version_build: null

cider_ci_link: https://github.com/cider-ci/cider-ci


hostname: localhost

basic_auth:
  user: ui
  secret: secret


api_service: 
  host: localhost
  port: 8885
  path: '/cider-ci/api/v2' 
  ssl: NULL

storage_service: 
  host: localhost
  port: 8883
  path: '/cider-ci/storage' 
  ssl: NULL


internal_api_service: 
  host: localhost
  port: 8885
  path: '/cider-ci/api/v2' 
  ssl: false

internal_builder_service: 
  host: 127.0.0.1 
  port: 8884
  path: '/cider-ci/builder' 
  ssl: false

internal_dispatcher_service: 
  host: 127.0.0.1 
  port: 8882
  path: '/cider-ci/dispatcher' 
  ssl: false

internal_repository_service: 
  host: 127.0.0.1 
  port: 8881
  path: '/cider-ci/repositories' 
  ssl: false

internal_storage_service: 
  host: localhost
  port: 8883
  path: '/cider-ci/storage' 
  ssl: false


http_server:
  host: 127.0.0.1
  port: 8888
  ssl: false


messaging: 

  connection: 

    vhost: cider-ci
    username: cider-ci
    password: cider-ci
    host: 127.0.0.1

