---
rows:
- name: Bash Demo Project
  items:
  - repository_name: Cider-CI Bash Demo Project
    branch_name: master
    execution_name: Test
  - repository_name: Cider-CI Bash Demo Project
    branch_name: wip
    execution_name: Test
  - repository_name: No repository
    branch_name: nix
    execution_name: No tests
