jobs:

  tests:

    name: Tests

    description: |
      Run specs under MRI.

    run-on:
    - type: branch
      include-match: ^.*$

    context:

      script-defaults:
        timeout: 300

      task-defaults:
        _cider-ci_include: 'cider-ci/shared/rails-defaults.yml'
        environment-variables:
          RAILS_ENV: test
          LANG: "en_US.UTF-8"

      traits:
        postgresql: true
        rbenv: true
        ruby: true

      tasks:
        specs:
          scripts:
            test:
              start-when:
              - script: bundle-mri
              - script: create-database
              body: bundle exec rspec spec/



